name: Test Docker Login

on:
  workflow_dispatch:

jobs:
  test-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          echo "DOCKERHUB_USERNAME is set? -> ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_TOKEN is set? -> ${{ secrets.DOCKERHUB_TOKEN }}"
      
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
